[package]
name = "backend"
version = "0.1.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
license = "MIT"
edition = "2018"

[lib]
name = "backend"
path = "src/lib.rs"

[dependencies]
ropey = "1"
# ropey = { git = "https://github.com/cessen/ropey", branch = "master" }
unicode-segmentation = "1"