[package]
name = "text_encoding"
version = "0.1.0"
authors = ["Nathan Vegdahl <cessen@cessen.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "text_encoding"
path = "src/lib.rs"

[dev-dependencies]
proptest = "0.8"